workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.example.tekhub"
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd tekhub
          flutter packages pub get
      - name: Flutter analyze
        script: |
          cd tekhub
          flutter analyze
      - name: Build APK with Flutter
        script: |
          cd tekhub
          flutter build apk --release
    artifacts:
      - tekhub/build/app/outputs/flutter-apk/app-release.apk
      - tekhub/flutter_drive.log

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120

    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          cd tekhub
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd tekhub
          flutter packages pub get
      - name: Install pods
        script: |
          cd tekhub
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          cd tekhub
          flutter analyze
      - name: Flutter build IPA
        script: |
          cd tekhub
          flutter build ipa --release
    artifacts:
      - tekhub/build/ios/ipa/*.ipa
      - tekhub/flutter_drive.log

  web-workflow:
    name: Web app workflow
    max_build_duration: 10
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd tekhub
          flutter packages pub get
      - name: Flutter analyze
        script: |
          cd tekhub
          flutter analyze
      - name: Flutter build webapp
        script: |
          cd tekhub
          flutter build web --release
          cd build/web
          7z a -r ../web.zip ./*
    artifacts:
      - tekhub/build/*.zip
