workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    scripts:
      - name: Set up local.properties
        script: |
          cd tekhub
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd tekhub
          flutter packages pub get
      - name: Flutter analyze
        script: |
          cd tekhub
          flutter analyze
      - name: Build AAB with Flutter
        script: |
          cd tekhub
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - antoine.hoareau@epitech.eu
        notify:
          success: true
          failure: false

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.tekhub # Replace with your actual iOS App ID
      vars:
        APP_ID: "com.example.tekhub" # Replace with your actual iOS App ID
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          cd tekhub
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd tekhub
          flutter packages pub get
      - name: Install pods
        script: |
          cd tekhub
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          cd tekhub
          flutter analyze
      - name: Flutter build ipa and automatic versioning
        script: |
          cd tekhub
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-app-store-build-number "$APP_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - antoine.hoareau@epitech.eu
        notify:
          success: true
          failure: false
      slack:
        channel: "#builds"
        notify_on_build_start: true
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - group name 1
        submit_to_app_store: false

  web-workflow:
    name: Web app workflow
    max_build_duration: 10
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd tekhub
          flutter packages pub get
      - name: Flutter analyze
        script: |
          cd tekhub
          flutter analyze
      - name: Flutter build webapp
        script: |
          cd tekhub
          flutter build web --release
          cd build/web
          7z a -r ../web.zip ./*
    artifacts:
      - build/web.zip
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - antoine.hoareau@epitech.eu
