name: tekhub
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  buttons_tabbar: ^1.3.8
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.13.2
  cupertino_icons: ^1.0.0
  file_picker: ^6.1.1
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_storage: ^11.5.3
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.0.4
  patterns_canvas: ^0.4.0
  flip_card: ^0.7.0
  location: ^5.0.3
  geocoding: ^2.1.1
  provider: ^5.0.0
  sidebarx: ^0.16.3

dev_dependencies:
  blackfoot_flutter_lint: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

fonts:
  - family: Raleway
    fonts:
      - asset: assets/fonts/Raleway-Regular.ttf
        weight: 400
      - asset: assets/fonts/Raleway-Bold.ttf
        weight: 700
      - asset: assets/fonts/Raleway-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Raleway-SemiBold.ttf
        weight: 600

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/circulomoradorelleno.png
    - assets/images/EllipseMorado.png
    - assets/images/ipad.png

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
