name: tekhub
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  blackfoot_flutter_lint: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

fonts:
  - family: Raleway
    fonts:
      - asset: assets/fonts/Raleway-Regular.ttf
        weight: 400
      - asset: assets/fonts/Raleway-Bold.ttf
        weight: 700
      - asset: assets/fonts/Raleway-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Raleway-SemiBold.ttf
        weight: 600

flutter:
  uses-material-design: true
