// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
    }
    return throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD40a0ymsxGbHZBkqjnQd1eTaxjodWfzcY',
    appId: '1:603475378308:web:cb8f5e86c70fd035ac02d1',
    messagingSenderId: '603475378308',
    projectId: 'flutter-d70dc',
    authDomain: 'flutter-d70dc.firebaseapp.com',
    storageBucket: 'flutter-d70dc.appspot.com',
    measurementId: 'G-BWWS9BJ28J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJnk_P7q2xxa5YDqnKNorvgkzInsC-MQs',
    appId: '1:603475378308:android:492fea26129c7fe4ac02d1',
    messagingSenderId: '603475378308',
    projectId: 'flutter-d70dc',
    storageBucket: 'flutter-d70dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Z3mmboV_239xV4yXjNTbBayBDnQ3lCc',
    appId: '1:603475378308:ios:307c823513d0ac7bac02d1',
    messagingSenderId: '603475378308',
    projectId: 'flutter-d70dc',
    storageBucket: 'flutter-d70dc.appspot.com',
    iosBundleId: 'com.example.tekhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_Z3mmboV_239xV4yXjNTbBayBDnQ3lCc',
    appId: '1:603475378308:ios:ca1e536e8f1a96a6ac02d1',
    messagingSenderId: '603475378308',
    projectId: 'flutter-d70dc',
    storageBucket: 'flutter-d70dc.appspot.com',
    iosBundleId: 'com.example.tekhub.RunnerTests',
  );
}
